---
#- name: Terminate instances
#  tasks:
#    - name: Terminate instances EC2
#      ec2:
#        state: "absent"
#        instance_ids: "{{ ids }}"

- local_action:
    module: ec2
    region: us-east-1
    instance_ids: "{{ ids }}"
    instance_tags:
        Name: poc_ansible
    state: absent
