---
- name: Criando instancia EC2 
  ec2:
    region: "{{ aws_region }}"
    key_name: redeteste
    instance_type: "{{ aws_instanceType }}"
    image: "{{ aws_base_amis }}"
    wait: yes
    group: "{{ security_group }}"
    count: "{{ count }}"
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: '{{ public_ip }}'
    private_ip: "{{ private_ip }}"
    state: present
    instance_tags:
      Name: poc_ansible
  register: ec2

- name: Alocar EIP
  ec2_eip: 
    instance_id: "{{ item.id }}"
    region: "{{ aws_region }}"
  with_items: 
    - '{{ ec2.instances }}'

- name: Adicionar instancia ao host group
  add_host: 
    hostname: "{{ item[0].private_ip }}"
    ec2_tag_Name: "{{ item[1] }}"
    groupname: launched
  with_together:
    - '{ ec2.instances }'
    - '{{ instances }}'

- name: teste
  debug:
    msg:  "{{ ec2.instances}}"



