---
- name: Criando instancia EC2 
  ec2:
    region: "{{ aws_region }}"
    key_name: redeteste
    instance_type: "{{ aws_instanceType }}"
    image: "{{ aws_base_amis }}"
    wait: yes
    group: "{{ security_group }}"
    count: "{{ count }}"
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: yes
    state: present
  register: ec2

- name: Adicionar instancia ao grupo
  add_host: hostname={{item[0].private_ip}} ec2_tag_Name={{item[1]}} groupname=launched
  with_together:
    - ec2.instances

