aws_base_amis: ami-f4cc1de2
ec2_name: poc_ansible
vpc_name: "poc_ansible"
vpc_cidr_block: "10.1.0.0/16"
aws_region: us-east-1
aws_zone: us-east-1a
key_priv: ~/redeteste.pem
security_group: "ec2_hosts"
public_ip: "yes"
subnet: subnet-f24e64a9
aws_instanceType: t2.micro
count: 1
cidr_ip2: 187.50.200.224/32
cidr_ip: 177.125.131.254/32
group_id: sg-5d653323
