--- 
- name: Criando instancia EC2
  ec2:
    key_name: redeteste
    group: default
    instance_type: t2.micro
    image: ami-5e63d13e
    ec2_url: ec2.us-west-2.amazonaws.com
    region: us-west-1
    vpc_subnet_id: subnet-13fc2a5a
    wait: yes
    count: 1
    assign_public_ip: yes
  register: ec2

- name: Adicionar instance ao host group 
  add_host: hostname={{item[0].private_ip}} groupname=server 
  with_together: 
    - ec2.instances 

- name: TAG Instances 
  ec2_tag: resource={{item[0].id}} region={{region}}
  args: 
    tags: { Name: "{{poc_ansible}}", Sigla: "WT", CVI_ID: "{{DP-2016-0028624}}", Ambiente: "{{DEV}}", FinalidadeFuncional: "{{Automacao EC2}}", FinalidadeArquitetura: "{{WEB}}", OS: "{{Ubuntu Server 16.04LTS}}", Provisionamento: "{{OffAt=06:00 / OnOff=22:00; Day=Every}}", Backup: "{{Window=00:00-2:00; Max=0:30; Day=Every}}", Creation: "{{Ansible v2.3}}" }
  with_together: 
    - ec2.instances 

- name: Aguardando SSH 
  wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started 
  with_items: ec2.instances
